env:
  sumocfg_path: scenarios/single_int/sim.sumocfg
  decision_interval_s: 5
  min_green_s: 10
  max_sim_time_s: 3600
  seed: 42

train:
  total_timesteps: 100000
  log_interval: 10
  save_freq_steps: 10000
  eval_freq_steps: 5000
  n_eval_episodes: 5
  eval_max_sim_time_s: 1800

sb3:
  learning_rate: 0.0001
  buffer_size: 10000
  batch_size: 128
  gamma: 0.999
  exploration_initial_eps: 0.9
  exploration_final_eps: 0.05
  target_update_interval: 1800
  train_freq: 1
  gradient_steps: 1
  policy_kwargs:
    net_arch:
      - 64
      - 32
