env:
  sumocfg_path: scenarios/single_int/sim.sumocfg
  decision_interval_s: 5
  min_green_s: 10
  max_sim_time_s: 300
  seed: 42

train:
  total_timesteps: 10000
  log_interval: 10
  save_freq_steps: 2500
  eval_freq_steps: 2500
  n_eval_episodes: 5
  eval_max_sim_time_s: 300

sb3:
  n_steps: 128
  batch_size: 32
  n_epochs: 4
  gamma: 0.999
  gae_lambda: 0.95
  clip_range: 0.2
  learning_rate: 0.00025
  policy_kwargs:
    net_arch:
      pi:
        - 64
        - 32
      vf:
        - 64
        - 32
