env:
  id: "LunarLander-v2"

seed: 123

train:
  total_steps: 2_000_000
  eval_every_steps: 25_000
  eval_episodes: 10
  log_every_steps: 1_000

model:
  hidden_sizes: [64, 64]
  activation: "tanh"

algo:
  name: "a2c"
  gamma: 0.99
  lr_actor: 0.001
  lr_critic: 0.001
  normalize_returns: true
  entropy_coef: 0.05  # Higher entropy bonus for more exploration
  max_grad_norm: 0.5
  n_steps: 5
